<?php
//DO NOT EDIT this file: or changes will be saved in GIT scm
//INSTEAD: rename this file to config_mirror.php (or copy it) and save your secrets
$mysql = array(
	'db_user' => '',
	'db_password' => '',
	'db_name' => ''
);

const BASE_URL	= 'http://local.forum/web/';
const MEDIA_URL = 'http://local.forum/web/media/';

const SYS_SALT	= 'MySecret'; //you get the idea ;)
ini_set('error_log', 'php_error.log');
ini_set('display_errors', 0);
