<?php
//DO NOT EDIT this file: or changes will be saved in GIT scm
//INSTEAD: rename this file to config_mirror.php (or copy it) and save your secrets
$mysql = array(
	'db_user' => '',
	'db_password' => '',
	'db_name' => ''
);